/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fantasypremierleague;

import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author win
 */
public class FantasyPremierLeague extends JFrame {
    static ArrayList <JComboBox> comboboxes ;
    static ArrayList <JLabel> pictures ;
    static ArrayList <JTextField> textfields ;
    static ArrayList <JLabel> opponents ;


    /**
     * Creates new form Fantasy
     */
    public FantasyPremierLeague() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        gk2Pic = new javax.swing.JLabel();
        gk1Pic = new javax.swing.JLabel();
        gk1TF = new javax.swing.JTextField();
        gk1CB = new javax.swing.JComboBox();
        gk1Opp = new javax.swing.JLabel();
        gk2TF = new javax.swing.JTextField();
        gk2CB = new javax.swing.JComboBox();
        gk2Opp = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        def1Pic = new javax.swing.JLabel();
        def1CB = new javax.swing.JComboBox();
        def1TF = new javax.swing.JTextField();
        def1Opp = new javax.swing.JLabel();
        def2Pic = new javax.swing.JLabel();
        def2TF = new javax.swing.JTextField();
        def2CB = new javax.swing.JComboBox();
        def2Opp = new javax.swing.JLabel();
        def3Pic = new javax.swing.JLabel();
        def3TF = new javax.swing.JTextField();
        def3CB = new javax.swing.JComboBox();
        def3Opp = new javax.swing.JLabel();
        def4Pic = new javax.swing.JLabel();
        def4TF = new javax.swing.JTextField();
        def4CB = new javax.swing.JComboBox();
        def4Opp = new javax.swing.JLabel();
        def5Pic = new javax.swing.JLabel();
        def5TF = new javax.swing.JTextField();
        def5CB = new javax.swing.JComboBox();
        def5Opp = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        gwTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        goButton = new javax.swing.JButton();
        loadB = new javax.swing.JButton();
        saveB = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        mid1Pic = new javax.swing.JLabel();
        mid1TF = new javax.swing.JTextField();
        mid1CB = new javax.swing.JComboBox();
        mid1Opp = new javax.swing.JLabel();
        mid2Pic = new javax.swing.JLabel();
        mid2TF = new javax.swing.JTextField();
        mid2CB = new javax.swing.JComboBox();
        mid2Opp = new javax.swing.JLabel();
        mid3Pic = new javax.swing.JLabel();
        mid3TF = new javax.swing.JTextField();
        mid3CB = new javax.swing.JComboBox();
        mid3Opp = new javax.swing.JLabel();
        mid4Pic = new javax.swing.JLabel();
        mid4TF = new javax.swing.JTextField();
        mid4CB = new javax.swing.JComboBox();
        mid4Opp = new javax.swing.JLabel();
        mid5Pic = new javax.swing.JLabel();
        mid5TF = new javax.swing.JTextField();
        mid5CB = new javax.swing.JComboBox();
        mid5Opp = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        fw1Pic = new javax.swing.JLabel();
        fw1TF = new javax.swing.JTextField();
        fw1CB = new javax.swing.JComboBox();
        fw1Opp = new javax.swing.JLabel();
        fw2Pic = new javax.swing.JLabel();
        fw2TF = new javax.swing.JTextField();
        fw2CB = new javax.swing.JComboBox();
        fw2Opp = new javax.swing.JLabel();
        fw3Pic = new javax.swing.JLabel();
        fw3TF = new javax.swing.JTextField();
        fw3CB = new javax.swing.JComboBox();
        fw3Opp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(56, 0, 60));

        jLabel1.setBackground(new java.awt.Color(51, 0, 153));
        jLabel1.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fantasy Premier League Gameweeks");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(191, 191, 191))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));

        gk2Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        gk2Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        gk2Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        gk1Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        gk1Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        gk1Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        gk1TF.setBackground(new java.awt.Color(64, 152, 106));
        gk1TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        gk1TF.setForeground(new java.awt.Color(255, 255, 255));
        gk1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gk1TF.setText("Goalkeeper");
        gk1TF.setAlignmentY(0.0F);
        gk1TF.setMargin(new java.awt.Insets(2, 2, 0, 2));

        gk1CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        gk1CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        gk1CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gk1CBActionPerformed(evt);
            }
        });

        gk1Opp.setBackground(new java.awt.Color(47, 252, 154));
        gk1Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        gk1Opp.setForeground(new java.awt.Color(36, 36, 36));
        gk1Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gk1Opp.setText("Opponent");
        gk1Opp.setOpaque(true);

        gk2TF.setBackground(new java.awt.Color(64, 152, 106));
        gk2TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        gk2TF.setForeground(new java.awt.Color(255, 255, 255));
        gk2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gk2TF.setText("Goalkeeper");

        gk2CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        gk2CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        gk2CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gk2CBActionPerformed(evt);
            }
        });

        gk2Opp.setBackground(new java.awt.Color(47, 252, 154));
        gk2Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        gk2Opp.setForeground(new java.awt.Color(36, 36, 36));
        gk2Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gk2Opp.setText("Opponent");
        gk2Opp.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(gk1Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(gk2Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(gk1CB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gk1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(gk1Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gk2Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gk2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gk2CB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(195, 195, 195))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gk2Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gk1Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gk1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gk2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gk1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gk2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gk2Opp)
                    .addComponent(gk1Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 255, 51));

        def1Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        def1Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        def1Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        def1CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        def1CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        def1CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                def1CBActionPerformed(evt);
            }
        });

        def1TF.setBackground(new java.awt.Color(64, 152, 106));
        def1TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        def1TF.setForeground(new java.awt.Color(255, 255, 255));
        def1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        def1TF.setText("Defender");

        def1Opp.setBackground(new java.awt.Color(47, 252, 154));
        def1Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        def1Opp.setForeground(new java.awt.Color(36, 36, 36));
        def1Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        def1Opp.setText("Opponent");
        def1Opp.setOpaque(true);

        def2Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        def2Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        def2Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        def2TF.setBackground(new java.awt.Color(64, 152, 106));
        def2TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        def2TF.setForeground(new java.awt.Color(255, 255, 255));
        def2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        def2TF.setText("Defender");

        def2CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        def2CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        def2CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                def2CBActionPerformed(evt);
            }
        });

        def2Opp.setBackground(new java.awt.Color(47, 252, 154));
        def2Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        def2Opp.setForeground(new java.awt.Color(36, 36, 36));
        def2Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        def2Opp.setText("Opponent");
        def2Opp.setOpaque(true);

        def3Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        def3Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        def3Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        def3TF.setBackground(new java.awt.Color(64, 152, 106));
        def3TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        def3TF.setForeground(new java.awt.Color(255, 255, 255));
        def3TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        def3TF.setText("Defender");

        def3CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        def3CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        def3CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                def3CBActionPerformed(evt);
            }
        });

        def3Opp.setBackground(new java.awt.Color(47, 252, 154));
        def3Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        def3Opp.setForeground(new java.awt.Color(36, 36, 36));
        def3Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        def3Opp.setText("Opponent");
        def3Opp.setOpaque(true);

        def4Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        def4Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        def4Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        def4TF.setBackground(new java.awt.Color(64, 152, 106));
        def4TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        def4TF.setForeground(new java.awt.Color(255, 255, 255));
        def4TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        def4TF.setText("Defender");

        def4CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        def4CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        def4CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                def4CBActionPerformed(evt);
            }
        });

        def4Opp.setBackground(new java.awt.Color(47, 252, 154));
        def4Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        def4Opp.setForeground(new java.awt.Color(36, 36, 36));
        def4Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        def4Opp.setText("Opponent");
        def4Opp.setOpaque(true);

        def5Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        def5Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        def5Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        def5TF.setBackground(new java.awt.Color(64, 152, 106));
        def5TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        def5TF.setForeground(new java.awt.Color(255, 255, 255));
        def5TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        def5TF.setText("Defender");

        def5CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        def5CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        def5CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                def5CBActionPerformed(evt);
            }
        });

        def5Opp.setBackground(new java.awt.Color(47, 252, 154));
        def5Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        def5Opp.setForeground(new java.awt.Color(36, 36, 36));
        def5Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        def5Opp.setText("Opponent");
        def5Opp.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(def1Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(def2Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(def3Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(def4Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(def5Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(def1CB, 0, 122, Short.MAX_VALUE)
                    .addComponent(def1TF))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(def2CB, 0, 122, Short.MAX_VALUE)
                    .addComponent(def2TF))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(def3CB, 0, 122, Short.MAX_VALUE)
                    .addComponent(def3TF))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(def4CB, 0, 122, Short.MAX_VALUE)
                    .addComponent(def4TF))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(def5CB, 0, 122, Short.MAX_VALUE)
                    .addComponent(def5TF))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(def1Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(def2Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(def3Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(def4Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(def5Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(def1Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def2Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def3Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def4Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def5Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(def1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def3CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def4CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def5CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(def5TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(def4TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(def3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(def1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(def2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(def3Opp)
                        .addComponent(def4Opp)
                        .addComponent(def5Opp)
                        .addComponent(def2Opp))
                    .addComponent(def1Opp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 135));

        gwTF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        gwTF.setText("Enter GW");

        jLabel2.setFont(new java.awt.Font("PremierLeagueW01-Regular", 0, 11)); // NOI18N
        jLabel2.setText("Gameweek:");

        goButton.setFont(new java.awt.Font("PremierLeagueW01-Regular", 0, 11)); // NOI18N
        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        loadB.setFont(new java.awt.Font("PremierLeagueW01-Regular", 0, 11)); // NOI18N
        loadB.setText("Load");
        loadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBActionPerformed(evt);
            }
        });

        saveB.setFont(new java.awt.Font("PremierLeagueW01-Regular", 0, 11)); // NOI18N
        saveB.setText("Save");
        saveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(gwTF, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(loadB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveB, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)))
                        .addGap(19, 19, 19))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gwTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goButton)
                .addGap(32, 32, 32)
                .addComponent(loadB)
                .addGap(31, 31, 31)
                .addComponent(saveB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 51));

        mid1Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        mid1Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        mid1Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        mid1TF.setBackground(new java.awt.Color(64, 152, 106));
        mid1TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        mid1TF.setForeground(new java.awt.Color(255, 255, 255));
        mid1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mid1TF.setText("Midfielder");

        mid1CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        mid1CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        mid1CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mid1CBActionPerformed(evt);
            }
        });

        mid1Opp.setBackground(new java.awt.Color(47, 252, 154));
        mid1Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        mid1Opp.setForeground(new java.awt.Color(36, 36, 36));
        mid1Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mid1Opp.setText("Opponent");
        mid1Opp.setOpaque(true);

        mid2Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        mid2Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        mid2Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        mid2TF.setBackground(new java.awt.Color(64, 152, 106));
        mid2TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        mid2TF.setForeground(new java.awt.Color(255, 255, 255));
        mid2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mid2TF.setText("Midfielder");

        mid2CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        mid2CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        mid2CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mid2CBActionPerformed(evt);
            }
        });

        mid2Opp.setBackground(new java.awt.Color(47, 252, 154));
        mid2Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        mid2Opp.setForeground(new java.awt.Color(36, 36, 36));
        mid2Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mid2Opp.setText("Opponent");
        mid2Opp.setOpaque(true);

        mid3Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        mid3Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        mid3Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        mid3TF.setBackground(new java.awt.Color(64, 152, 106));
        mid3TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        mid3TF.setForeground(new java.awt.Color(255, 255, 255));
        mid3TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mid3TF.setText("Midfielder");

        mid3CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        mid3CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        mid3CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mid3CBActionPerformed(evt);
            }
        });

        mid3Opp.setBackground(new java.awt.Color(47, 252, 154));
        mid3Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        mid3Opp.setForeground(new java.awt.Color(36, 36, 36));
        mid3Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mid3Opp.setText("Opponent");
        mid3Opp.setOpaque(true);

        mid4Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        mid4Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        mid4Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        mid4TF.setBackground(new java.awt.Color(64, 152, 106));
        mid4TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        mid4TF.setForeground(new java.awt.Color(255, 255, 255));
        mid4TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mid4TF.setText("Midfielder");

        mid4CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        mid4CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        mid4CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mid4CBActionPerformed(evt);
            }
        });

        mid4Opp.setBackground(new java.awt.Color(47, 252, 154));
        mid4Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        mid4Opp.setForeground(new java.awt.Color(36, 36, 36));
        mid4Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mid4Opp.setText("Opponent");
        mid4Opp.setOpaque(true);

        mid5Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        mid5Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        mid5Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        mid5TF.setBackground(new java.awt.Color(64, 152, 106));
        mid5TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        mid5TF.setForeground(new java.awt.Color(255, 255, 255));
        mid5TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mid5TF.setText("Midfielder");

        mid5CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        mid5CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        mid5CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mid5CBActionPerformed(evt);
            }
        });

        mid5Opp.setBackground(new java.awt.Color(47, 252, 154));
        mid5Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        mid5Opp.setForeground(new java.awt.Color(36, 36, 36));
        mid5Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mid5Opp.setText("Opponent");
        mid5Opp.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(mid1Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(mid2Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE)
                .addComponent(mid3Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(mid4Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(mid5Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mid1CB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mid2CB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mid3CB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mid4CB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mid5CB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mid1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid1Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mid2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid2Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mid3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid3Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(mid4Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mid5Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(mid4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mid5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mid1Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid2Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid3Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid4Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid5Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mid1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid3CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid4CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid5CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mid1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid4TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mid5TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mid1Opp)
                    .addComponent(mid2Opp)
                    .addComponent(mid3Opp)
                    .addComponent(mid4Opp)
                    .addComponent(mid5Opp))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 255, 51));

        fw1Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        fw1Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        fw1Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        fw1TF.setBackground(new java.awt.Color(64, 152, 106));
        fw1TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        fw1TF.setForeground(new java.awt.Color(255, 255, 255));
        fw1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fw1TF.setText("Forward");

        fw1CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        fw1CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        fw1CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fw1CBActionPerformed(evt);
            }
        });

        fw1Opp.setBackground(new java.awt.Color(47, 252, 154));
        fw1Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        fw1Opp.setForeground(new java.awt.Color(36, 36, 36));
        fw1Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fw1Opp.setText("Opponent");
        fw1Opp.setOpaque(true);

        fw2Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        fw2Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        fw2Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        fw2TF.setBackground(new java.awt.Color(64, 152, 106));
        fw2TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        fw2TF.setForeground(new java.awt.Color(255, 255, 255));
        fw2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fw2TF.setText("Forward");

        fw2CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        fw2CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        fw2CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fw2CBActionPerformed(evt);
            }
        });

        fw2Opp.setBackground(new java.awt.Color(47, 252, 154));
        fw2Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        fw2Opp.setForeground(new java.awt.Color(36, 36, 36));
        fw2Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fw2Opp.setText("Opponent");
        fw2Opp.setOpaque(true);

        fw3Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Default.png"))); // NOI18N
        fw3Pic.setMaximumSize(new java.awt.Dimension(50, 64));
        fw3Pic.setMinimumSize(new java.awt.Dimension(50, 64));

        fw3TF.setBackground(new java.awt.Color(64, 152, 106));
        fw3TF.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        fw3TF.setForeground(new java.awt.Color(255, 255, 255));
        fw3TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fw3TF.setText("Forward");

        fw3CB.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 11)); // NOI18N
        fw3CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Team", "Arsenal", "Bournemouth", "Brighton", "Burnley", "Cardiff", "Chelsea", "Crystal Palace", "Everton", "Fulham", "Huddersfield", "Leicester", "Liverpool", "Man City", "Man Utd", "Newcastle", "Southampton", "Spurs", "Watford", "West Ham", "Wolves" }));
        fw3CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fw3CBActionPerformed(evt);
            }
        });

        fw3Opp.setBackground(new java.awt.Color(47, 252, 154));
        fw3Opp.setFont(new java.awt.Font("PremierLeagueW01-Bold", 0, 14)); // NOI18N
        fw3Opp.setForeground(new java.awt.Color(36, 36, 36));
        fw3Opp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fw3Opp.setText("Opponent");
        fw3Opp.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fw1CB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fw1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fw1Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(fw2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fw3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(fw2CB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fw3CB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(fw2Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fw3Opp, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(fw1Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(fw2Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(fw3Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fw1Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fw2Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fw3Pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fw1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fw2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fw3CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fw2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fw1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fw3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fw1Opp)
                    .addComponent(fw2Opp)
                    .addComponent(fw3Opp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void def2CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_def2CBActionPerformed
        if(def2CB.getSelectedItem()=="Select Team")
        def2Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        def2Pic.setIcon(new ImageIcon("src/"+def2CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_def2CBActionPerformed

    private void gk1CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gk1CBActionPerformed
        if(gk1CB.getSelectedItem()=="Select Team")
        gk1Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        gk1Pic.setIcon(new ImageIcon("src/"+gk1CB.getSelectedItem()+" GK.png") );
    }//GEN-LAST:event_gk1CBActionPerformed

    private void def1CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_def1CBActionPerformed
        if(def1CB.getSelectedItem()=="Select Team")
        def1Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        def1Pic.setIcon(new ImageIcon("src/"+def1CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_def1CBActionPerformed

    private void def3CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_def3CBActionPerformed
        if(def3CB.getSelectedItem()=="Select Team")
        def3Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        def3Pic.setIcon(new ImageIcon("src/"+def3CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_def3CBActionPerformed

    private void def4CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_def4CBActionPerformed
        if(def4CB.getSelectedItem()=="Select Team")
        def4Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        def4Pic.setIcon(new ImageIcon("src/"+def4CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_def4CBActionPerformed

    private void def5CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_def5CBActionPerformed
        if(def5CB.getSelectedItem()=="Select Team")
        def5Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        def5Pic.setIcon(new ImageIcon("src/"+def5CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_def5CBActionPerformed

    private void mid1CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mid1CBActionPerformed
        if(mid1CB.getSelectedItem()=="Select Team")
        mid1Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        mid1Pic.setIcon(new ImageIcon("src/"+mid1CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_mid1CBActionPerformed

    private void mid2CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mid2CBActionPerformed
        if(mid2CB.getSelectedItem()=="Select Team")
        mid2Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        mid2Pic.setIcon(new ImageIcon("src/"+mid2CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_mid2CBActionPerformed

    private void mid3CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mid3CBActionPerformed
        if(mid3CB.getSelectedItem()=="Select Team")
        mid3Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        mid3Pic.setIcon(new ImageIcon("src/"+mid3CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_mid3CBActionPerformed

    private void mid4CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mid4CBActionPerformed
        if(mid4CB.getSelectedItem()=="Select Team")
        mid4Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        mid4Pic.setIcon(new ImageIcon("src/"+mid4CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_mid4CBActionPerformed

    private void mid5CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mid5CBActionPerformed
        if(mid5CB.getSelectedItem()=="Select Team")
        mid5Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        mid5Pic.setIcon(new ImageIcon("src/"+mid5CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_mid5CBActionPerformed

    private void fw1CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fw1CBActionPerformed
        if(fw1CB.getSelectedItem()=="Select Team")
        fw1Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        fw1Pic.setIcon(new ImageIcon("src/"+fw1CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_fw1CBActionPerformed

    private void fw2CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fw2CBActionPerformed
        if(fw2CB.getSelectedItem()=="Select Team")
        //fw2Pic.setIcon(new ImageIcon(getClass().getResource("Default.png")) );    
        fw2Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        //fw2Pic.setIcon(new ImageIcon(getClass().getResource(""+fw2CB.getSelectedItem()+".png")) );    
        fw2Pic.setIcon(new ImageIcon("src/"+fw2CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_fw2CBActionPerformed

    private void fw3CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fw3CBActionPerformed
        if(fw3CB.getSelectedItem()=="Select Team")
        fw3Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        fw3Pic.setIcon(new ImageIcon("src/"+fw3CB.getSelectedItem()+".png") );
    }//GEN-LAST:event_fw3CBActionPerformed

    private void gk2CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gk2CBActionPerformed
        if(gk2CB.getSelectedItem()=="Select Team")
        gk2Pic.setIcon(new ImageIcon("src/Default.png") );
        else
        gk2Pic.setIcon(new ImageIcon("src/"+gk2CB.getSelectedItem()+" GK.png") );
    }//GEN-LAST:event_gk2CBActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        comboboxes = new ArrayList<JComboBox>(Arrays.asList(gk1CB,gk2CB,def1CB,def2CB,def3CB,def4CB,def5CB,mid1CB,mid2CB,mid3CB,mid4CB,mid5CB,fw1CB,fw2CB,fw3CB));       
        opponents =new ArrayList<JLabel>(Arrays.asList(gk1Opp,gk2Opp,def1Opp,def2Opp,def3Opp,def4Opp,def5Opp,mid1Opp,mid2Opp,mid3Opp,mid4Opp,mid5Opp,fw1Opp,fw2Opp,fw3Opp)) ;
        int gw = 0 , i = 0 , c = 0;
        try {
        gw = Integer.parseInt(gwTF.getText());
        if(gw > 38 || gw < 1)
             JOptionPane.showMessageDialog(null,"Wrong value");
        else{
        for(i = 0 ; i<15  ;i++){
            if(comboboxes.get(i).getSelectedItem().equals("Select Team"))
            c++;
        }
        if(c>0)
            JOptionPane.showMessageDialog(null,c+" field is empty");
        else{
        for(i = 0 ; i<15  ;i++){    
        ResultSet result = statement.executeQuery("SELECT Opponent FROM Fixtures where GW = "+gw+" AND Team = '"+comboboxes.get(i).getSelectedItem()+"' ");
        result.next();
        opponents.get(i).setText(result.getString("Opponent"));}
        }
        }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null,"Wrong input");
        }
         catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"SQLException");
        }
 
    }//GEN-LAST:event_goButtonActionPerformed

    private void loadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBActionPerformed
        comboboxes = new ArrayList<JComboBox>(Arrays.asList(gk1CB,gk2CB,def1CB,def2CB,def3CB,def4CB,def5CB,mid1CB,mid2CB,mid3CB,mid4CB,mid5CB,fw1CB,fw2CB,fw3CB));       
        pictures = new ArrayList<JLabel>(Arrays.asList(gk1Pic,gk2Pic,def1Pic,def2Pic,def3Pic,def4Pic,def5Pic,mid1Pic,mid2Pic,mid3Pic,mid4Pic,mid5Pic,fw1Pic,fw2Pic,fw3Pic)) ;
        textfields = new ArrayList<JTextField>(Arrays.asList(gk1TF,gk2TF,def1TF,def2TF,def3TF,def4TF,def5TF,mid1TF,mid2TF,mid3TF,mid4TF,mid5TF,fw1TF,fw2TF,fw3TF)) ;
            try {
                for(int i=0 ; i<15 ; i++){
                ResultSet result = statement.executeQuery("SELECT Player , Team FROM Players where ID = "+(i+1)+"  ");
                result.next();
                comboboxes.get(i).setSelectedItem(result.getString("Team"));
                if(i<2)
                pictures.get(i).setIcon(new ImageIcon("src/"+result.getString("Team")+" GK.png") );
                else
                pictures.get(i).setIcon(new ImageIcon("src/"+result.getString("Team")+".png") );
                textfields.get(i).setText(result.getString("Player"));}
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"SQLException");            
            }        
    }//GEN-LAST:event_loadBActionPerformed

    private void saveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBActionPerformed
        int c = 0 ;
        comboboxes = new ArrayList<JComboBox>(Arrays.asList(gk1CB,gk2CB,def1CB,def2CB,def3CB,def4CB,def5CB,mid1CB,mid2CB,mid3CB,mid4CB,mid5CB,fw1CB,fw2CB,fw3CB));       
        textfields = new ArrayList<JTextField>(Arrays.asList(gk1TF,gk2TF,def1TF,def2TF,def3TF,def4TF,def5TF,mid1TF,mid2TF,mid3TF,mid4TF,mid5TF,fw1TF,fw2TF,fw3TF)) ;
        for(int i = 0 ; i<15  ;i++){
        if(comboboxes.get(i).getSelectedItem().equals("Select Team"))
        c++;
        } 
        if(c>0)
            JOptionPane.showMessageDialog(null,c+" field is empty");
        else{
        try {
            for(int i=0 ; i<15 ; i++){
                statement.executeUpdate("UPDATE Players SET (Team,Player) = ('"+comboboxes.get(i).getSelectedItem()+"','"+textfields.get(i).getText()+"') WHERE ID = "+(i+1)+" ");}
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"SQLException");            
            }
        }
    }//GEN-LAST:event_saveBActionPerformed
    
    
    public static void main(String args[]) throws ClassNotFoundException, SQLException {        
        Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
       // connection = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/win/Documents/NetBeansProjects/FantasyPremierLeague/src/PLFixtures.accdb");        
        connection = DriverManager.getConnection("jdbc:ucanaccess://src/PLFixtures.accdb");
        statement = connection.createStatement();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FantasyPremierLeague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FantasyPremierLeague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FantasyPremierLeague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FantasyPremierLeague.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FantasyPremierLeague().setVisible(true);
            }
        });
    }
    static Connection connection;
    static Statement statement;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox def1CB;
    private static javax.swing.JLabel def1Opp;
    private static javax.swing.JLabel def1Pic;
    private static javax.swing.JTextField def1TF;
    private static javax.swing.JComboBox def2CB;
    private static javax.swing.JLabel def2Opp;
    private static javax.swing.JLabel def2Pic;
    private static javax.swing.JTextField def2TF;
    private static javax.swing.JComboBox def3CB;
    private static javax.swing.JLabel def3Opp;
    private static javax.swing.JLabel def3Pic;
    private static javax.swing.JTextField def3TF;
    private static javax.swing.JComboBox def4CB;
    private static javax.swing.JLabel def4Opp;
    private static javax.swing.JLabel def4Pic;
    private static javax.swing.JTextField def4TF;
    private static javax.swing.JComboBox def5CB;
    private static javax.swing.JLabel def5Opp;
    private static javax.swing.JLabel def5Pic;
    private static javax.swing.JTextField def5TF;
    private static javax.swing.JComboBox fw1CB;
    private static javax.swing.JLabel fw1Opp;
    private static javax.swing.JLabel fw1Pic;
    private static javax.swing.JTextField fw1TF;
    private static javax.swing.JComboBox fw2CB;
    private static javax.swing.JLabel fw2Opp;
    private static javax.swing.JLabel fw2Pic;
    private static javax.swing.JTextField fw2TF;
    private static javax.swing.JComboBox fw3CB;
    private static javax.swing.JLabel fw3Opp;
    private static javax.swing.JLabel fw3Pic;
    private static javax.swing.JTextField fw3TF;
    private static javax.swing.JComboBox gk1CB;
    private static javax.swing.JLabel gk1Opp;
    private static javax.swing.JLabel gk1Pic;
    private static javax.swing.JTextField gk1TF;
    private static javax.swing.JComboBox gk2CB;
    private static javax.swing.JLabel gk2Opp;
    private static javax.swing.JLabel gk2Pic;
    private static javax.swing.JTextField gk2TF;
    private static javax.swing.JButton goButton;
    private static javax.swing.JTextField gwTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private static javax.swing.JButton loadB;
    private static javax.swing.JComboBox mid1CB;
    private static javax.swing.JLabel mid1Opp;
    private static javax.swing.JLabel mid1Pic;
    private static javax.swing.JTextField mid1TF;
    private static javax.swing.JComboBox mid2CB;
    private static javax.swing.JLabel mid2Opp;
    private static javax.swing.JLabel mid2Pic;
    private static javax.swing.JTextField mid2TF;
    private static javax.swing.JComboBox mid3CB;
    private static javax.swing.JLabel mid3Opp;
    private static javax.swing.JLabel mid3Pic;
    private static javax.swing.JTextField mid3TF;
    private static javax.swing.JComboBox mid4CB;
    private static javax.swing.JLabel mid4Opp;
    private static javax.swing.JLabel mid4Pic;
    private static javax.swing.JTextField mid4TF;
    private static javax.swing.JComboBox mid5CB;
    private static javax.swing.JLabel mid5Opp;
    private static javax.swing.JLabel mid5Pic;
    private static javax.swing.JTextField mid5TF;
    private static javax.swing.JButton saveB;
    // End of variables declaration//GEN-END:variables
        
}
